USE sucos;

-- USAMOS A FUNCAO "ADD COLUMN" PARA ADICIONAR UMA NOVA COLUNA E DENTRO DOS PARENTESES ESPECIFICAMOS O NOME DO CAMPO + O TIPO DELE;

SELECT * FROM tbcliente;

ALTER TABLE tbcliente ADD COLUMN (DATA_NASCIMENTO DATE);

-- VAMOS INSERIR UM CLIENTE

INSERT INTO tbcliente(CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO, 
VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO)
 VALUES ('12345678910','Ricardo Jonas da Silva','rua 1','rua 2','vila 1','Sao paulo','SP','02345000',28,'M',10000,20000,0,'1991-05-24'); 