USE sucos;
-- PARA ALTERAR OS REGISTROS UTILIZAMOS A FUNCAO "UPDATE" + O NOME DA TABELA SEGUIDO DA PALAVRA "SET" ONDE VAMOS COLOCAR O NOME DO CAMPO A SER ALTERADO JUNTO COM O NOVO VALOR APOS 0 =
-- ONDE UTILIZAREMOS A PALAVRA "WHERE" ESPECIFICANDO QUAL REGISTRO DEVE SER ALTERADO

UPDATE tbproduto SET EMBALAGEM = 'Lata', PRECO_LISTA = 2.45
WHERE PRODUTO = '544931';

UPDATE tbproduto SET EMBALAGEM = 'Garrafa'
WHERE PRODUTO = '1078680';
SELECT * FROM tbproduto;
