USE sucos;
-- PARA ALTERAR OS REGISTROS UTILIZAMOS A FUNCAO "UPDATE" + O NOME DA TABELA SEGUIDO DA PALAVRA "SET" ONDE VAMOS COLOCAR O NOME DO CAMPO A SER ALTERADO JUNTO COM O NOVO VALOR APOS 0 =
-- ONDE UTILIZAREMOS A PALAVRA "WHERE" ESPECIFICANDO QUAL REGISTRO DEVE SER ALTERADO

UPDATE tbvendedores SET percentual_comissao = 1.1
WHERE matricula ='00236';

UPDATE tbvendedores SET NOME ='Jose Geraldo da Fonseca Junior' 
WHERE matricula ='00233';


select * from tbvendedores;

