USE sucos;

DROP TABLE IF EXISTS tbvendedores;

CREATE TABLE tbvendedores(
	MATRICULA varchar(5),
    NOME 	varchar(100),
    PERCENTUAL_COMISSAO FLOAT,
    DATA_ADMISSAO DATE,
    DE_FERIAS BIT);
    
 ALTER TABLE tbvendedores ADD PRIMARY KEY(MATRICULA);
 
 INSERT INTO tbvendedores(
MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS) VALUES ('00235','Marcio Almeida Silva',0.8,'2014-08-15',0);
 
 INSERT INTO tbvendedores(
MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS) VALUES ('00236','Claudia Morais',0.8,'2013-09-17',1); 
 
 INSERT INTO tbvendedores(
MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS) VALUES ('00237','Roberta Martins',1.1,'2017-03-18',1); 
 
 INSERT INTO tbvendedores(
MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,DE_FERIAS) VALUES ('00238','Pericles Alves',1.1,'2016-08-21',0); 
 
SELECT * FROM tbvendedores;