
CREATE TABLE tbvendedores(
matricula VARCHAR(5),
nome VARCHAR (100),
percentual_comissao FLOAT);

-- AQUI CRIAMOS UMA SITUACAO ONDE SEM QUERER ACRESCENTAMOS UMA TABELA ONDE CONTEM DADOS IGUAIS A OUTRA TABELA,VAMOS UTILIZAR O DROP PARA APAGAR ESSA TABELA

CREATE TABLE tbvendedores2(
matricula VARCHAR(5),
nome VARCHAR (100),
percentual_comissao FLOAT);

-- APAGANDO A TABELA 

DROP TABLE tbvendedores2;


