-- UTILIZAMOS O "USE" PARA SELECIONAR UM BANCO DE DADOS,SERVE COMO FOSSE UM DUPLO CLIQUE EM CIMA DO NOME DO BANCO DE DADOS 
USE SUCOS;

-- PARA CRIAR UMA TABELA UTILIZAMOS A FUNCAO "CREATE TABLE" + O NOME DA TABELA,PASSANDO AS INFORMACOES A SEREM INSERIDAS DENTRO DA TABELA E O TIPO 


CREATE TABLE tbcliente
( CPF VARCHAR (11) ,
NOME VARCHAR (100) ,
ENDERECO1 VARCHAR (150) ,
ENDERECO2 VARCHAR (150) ,
BAIRRO VARCHAR (50) ,
CIDADE VARCHAR (50) ,
ESTADO VARCHAR (2) ,
CEP VARCHAR (8) ,
IDADE SMALLINT,
SEXO VARCHAR (1) ,
LIMITE_CREDITO FLOAT ,
VOLUME_COMPRA FLOAT ,
PRIMEIRA_COMPRA BIT );


-- APAGANDO A TABELA,UTILIZAMOS DROP TABLE + O NOME DA TABELA

DROP TABLE tbcliente;