-- UTILIZAMOS PARA APAGAR O BANCO DE DADOS  A FUNCAO DROP,CASO EXISTA O BANCO "SUCOS" DROPA ELE E EM SEGUIDA CRIAMOS NOVAMENTE O BANCO;
DROP DATABASE IF EXISTS SUCOS;

-- CRIANDO O BANCO DE DADOS; 
CREATE DATABASE SUCOS;