-- PARA INSERIR QUALQUER DADO NA TABELA UTILIZAMOS A FUNCAO 'INSERT INTO + O NOME DA TABELA.
-- ATENCAO!! TODA VEZ QUE INSERIRMOS DADOS DENTRO DA TABELA TEM QUE ESTAR NA RESPECTIVA ORDEM E TIPO,NAO PODEMOS COLOCAR UM NUMERO DENTRO DE UM VARCHAR,
-- TODO VARCHAR E CONSIDERADO UMA STRING E TEM QUE ESTAR DENTRO DE ' ' ASPAS SIMPLES
-- APOS COLOCAR  AS COLUNAS DEVEMOS INSERIR OS REGISTROS ATRAVÉS DA FUNCAO VALUES
INSERT INTO tbproduto(
PRODUTO, 
NOME,  
EMBALAGEM,  
TAMANHO,  
SABOR,  
PRECO_LISTA) VALUES('1040107','light -350ml-MeLancia','lata','350ml','Melancia',4.56);


INSERT INTO tbproduto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml','Limão',3.20);

INSERT INTO tbproduto (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);

select * from tbproduto;